@startuml

title Pacotes da Rota Sul

package "br.uni9.rotasul" {

  package "pedido" {
    package "pedido.web" as pedidoWeb {
      class PedidoController
    }

    package "pedido.service" as pedidoService {
      class PedidoService
    }

    package "pedido.repository" as pedidoRepository {
      interface PedidoRepository
    }

    package "pedido.domain" as pedidoDomain {
      class Pedido
    }
  }

  package "expedicao" {
    package "expedicao.web" as expedicaoWeb {
      class RemessaController
    }

    package "expedicao.service" as expedicaoService {
      class RemessaService
    }

    package "expedicao.repository" as expedicaoRepository {
      interface RemessaRepository
    }

    package "expedicao.domain" as expedicaoDomain {
      class Remessa
    }
  }

  package "rastreamento" {
    package "rastreamento.web" as rastreamentoWeb {
      class OcorrenciaController
    }

    package "rastreamento.service" as rastreamentoService {
      class OcorrenciaService
    }

    package "rastreamento.repository" as rastreamentoRepository {
      interface OcorrenciaRepository
    }

    package "rastreamento.domain" as rastreamentoDomain {
      class Ocorrencia
    }
  }
}

pedidoWeb ..> pedidoService
pedidoService ..> pedidoRepository
pedidoService ..> pedidoDomain
pedidoRepository ..> pedidoDomain

expedicaoWeb ..> expedicaoService
expedicaoService ..> expedicaoRepository
expedicaoService ..> expedicaoDomain
expedicaoRepository ..> expedicaoDomain

rastreamentoWeb ..> rastreamentoService
rastreamentoService ..> rastreamentoRepository
rastreamentoService ..> rastreamentoDomain
rastreamentoRepository ..> rastreamentoDomain

@enduml